### ISSUE TITLE
vfu not honoring 'Editor' assignment in config file

### ISSUE THREAD

**Issue by andy5995** [cade-vs/vfu#17]
In ~/.vfu/vfu.conf I have Editor set to nano, but vfu always ignores it and uses the internal editor.

**Comment by andy5995** [comment]
I see now if I use "o" I can toggle off the internal editor.

**Comment by cade-vs** [comment]
hi!

sorry for the delay.

you have to disable "use the internal editor" option from the options menu: key "O" inside VFU.

tell me if this solves the problem?

thanks.
P! Vladi.
-



On Wed, 24 Aug 2022 13:15:57 -0700
Andy Alt ***@***.***> wrote:

> In ~/.vfu/vfu.conf I have Editor set to nano, but vfu always ignores it and uses the internal editor.
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/cade-vs/vfu/issues/17
> You are receiving this because you are subscribed to this thread.
> 
> Message ID: ***@***.***>


-- 
Vladi Belperchinov-Shabanski  
      ***@***.***> ***@***.***>
http://cade.noxrun.com
pgp/gpg key 6F35B214 @ http://pgp.mit.edu

**Comment by andy5995** [comment]
Yes, solved. :) See my second post in this thread. Thanks for the response anyway.
